[project]
name = "movie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.114.0",
    "pydantic>=2.9.1",
    "pymongo[srv]>=4.8.0",
]
